[app]
[app.ble]
device_name = 'PinLevel'

[app.waveform]
buffer_size = 256
log_knee = 0.02
force_yellow_g = 0.03
force_red_g = 0.1
amp_scale = 1.0
swap_xy = true

[app.viz]
width = 608
height = 1080

[server]
port = ':8091'
