[app]
[app.ble]
device_address = 'EA:F0:F1:BC:59:DD'
device_name = 'WT901BLE68'
sensor_name = 'WT901'

[app.waveform]
buffer_size = 256
log_knee = 0.02
force_yellow_g = 0.03
force_red_g = 0.1
amp_scale = 1.0
swap_xy = false

[app.crosshair]
force_yellow_g = 0.196
force_red_g = 0.36
smoothing = 0.7
segment_size = 9
bar_thickness = 10
swap_xy = false

[app.viz]
width = 200
height = 200

[app.auto_lock]
timeout = 10.0
epsilon = 0.01

[app.obs]
host = 'localhost'
port = 4455
password = ''
scene_name = 'Scene'
source_name = 'Browser 3'

[server]
port = ':8091'
