/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ble/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble connect */
        post: operations["post-api-ble-connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble disconnect */
        post: operations["post-api-ble-disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API ble frame */
        get: operations["get-api-ble-frame"];
        put?: never;
        /** Post API ble frame */
        post: operations["post-api-ble-frame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * BLE scan SSE stream
         * @description Opening this connection starts scanning; closing it stops scanning
         */
        get: operations["ble-scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config */
        get: operations["get-api-config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/auto_lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config auto lock */
        get: operations["get-api-config-auto-lock"];
        /** Put API config auto lock */
        put: operations["put-api-config-auto-lock"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/ble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config ble */
        get: operations["get-api-config-ble"];
        /** Put API config ble */
        put: operations["put-api-config-ble"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/crosshair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config crosshair */
        get: operations["get-api-config-crosshair"];
        /** Put API config crosshair */
        put: operations["put-api-config-crosshair"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/display": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config display */
        get: operations["get-api-config-display"];
        /** Put API config display */
        put: operations["put-api-config-display"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config experiment */
        get: operations["get-api-config-experiment"];
        /** Put API config experiment */
        put: operations["put-api-config-experiment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/sensor/WT901": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config sensor wt901 */
        get: operations["get-api-config-sensor-wt901"];
        /** Put API config sensor wt901 */
        put: operations["put-api-config-sensor-wt901"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config waveform */
        get: operations["get-api-config-waveform"];
        /** Put API config waveform */
        put: operations["put-api-config-waveform"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE event stream
         * @description Real-time orientation data and BLE status events
         */
        get: operations["events-stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AutoLockConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AutoLockConfig.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description Stdev threshold (g) to trigger lock
             * @default 0.005
             */
            spread_threshold: number;
            /**
             * Format: double
             * @description Sliding window duration (s)
             * @default 5
             */
            spread_window: number;
        };
        BLEConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BLEConfig.json
             */
            readonly $schema?: string;
            device_address: string;
            device_name: string;
            sensor_name: string;
        };
        BLEScanResultEvent: {
            address: string;
            name: string;
            /** Format: int64 */
            rssi: number;
            sensor_name?: string;
            timestamp: string;
        };
        BLEStatusEvent: {
            device?: string;
            device_name?: string;
            reason?: string;
            sensor_name?: string;
            status: string;
            timestamp: string;
        };
        BatteryEvent: {
            /** Format: int32 */
            battery_percent: number;
            /** Format: float */
            battery_volts: number;
            charging: boolean;
            timestamp: string;
        };
        ConfigChangedEvent: {
            section: string;
            timestamp: string;
        };
        ConnectRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ConnectRequestBody.json
             */
            readonly $schema?: string;
            /**
             * @description BLE MAC address
             * @example AA:BB:CC:DD:EE:FF
             */
            address: string;
            /**
             * @description BLE advertised name
             * @example WT901BLE50
             */
            name: string;
        };
        CrosshairConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CrosshairConfig.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Bar thickness (px)
             * @default 12
             */
            bar_thickness: number;
            /**
             * Format: double
             * @description Decay time (s)
             * @default 0.3
             */
            decay_s: number;
            /**
             * @description Enable visualization
             * @default true
             */
            enabled: boolean;
            /**
             * Format: double
             * @description Red threshold (g)
             * @default 0.1
             */
            force_red_g: number;
            /**
             * Format: double
             * @description Yellow threshold (g)
             * @default 0.03
             */
            force_yellow_g: number;
            /**
             * Format: int64
             * @description Canvas height (px)
             * @default 1080
             */
            height: number;
            /**
             * @description Hide negative Y arm
             * @default false
             */
            hide_neg_y: boolean;
            /**
             * Format: int64
             * @description Bar segment size (px)
             * @default 10
             */
            segment_size: number;
            /**
             * Format: int64
             * @description Canvas width (px)
             * @default 608
             */
            width: number;
        };
        DelayedOrientationEvent: {
            /** Format: float */
            g: number;
            timestamp: string;
            /** Format: float */
            x: number;
            /** Format: float */
            y: number;
        };
        DisplayConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DisplayConfig.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Delay sensor readings (ms)
             * @default 0
             */
            delay_ms: number;
            /**
             * @description Visible duration after trigger (s)
             * @default 5
             */
            fade_s: -1 | number;
            /**
             * @description Swap X and Y axes
             * @default false
             */
            swap_xy: boolean;
            /**
             * Format: double
             * @description Movement threshold on X/Y axes (g)
             * @default 0.02
             */
            trigger_g: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ExperimentConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ExperimentConfig.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description Decay time (s)
             * @default 0.3
             */
            decay_s: number;
            /**
             * @description Enable visualization
             * @default true
             */
            enabled: boolean;
            /**
             * Format: double
             * @description Red threshold (g)
             * @default 0.1
             */
            force_red_g: number;
            /**
             * Format: double
             * @description Yellow threshold (g)
             * @default 0.03
             */
            force_yellow_g: number;
            /**
             * Format: int64
             * @description Canvas height (px)
             * @default 1080
             */
            height: number;
            /**
             * Format: int64
             * @description Canvas width (px)
             * @default 608
             */
            width: number;
        };
        FrameActionRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FrameActionRequestBody.json
             */
            readonly $schema?: string;
            /**
             * @description Action to perform
             * @example enable
             * @enum {string}
             */
            action: "enable" | "disable" | "trigger";
        };
        FrameStateBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FrameStateBody.json
             */
            readonly $schema?: string;
            locked: boolean;
        };
        HeartbeatEvent: {
            timestamp: string;
        };
        LogEntry: {
            level: string;
            message: string;
            timestamp: string;
        };
        OKBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OKBody.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        PinQuakeConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PinQuakeConfig.json
             */
            readonly $schema?: string;
            auto_lock: components["schemas"]["AutoLockConfig"];
            ble: components["schemas"]["BLEConfig"];
            crosshair: components["schemas"]["CrosshairConfig"];
            display: components["schemas"]["DisplayConfig"];
            experiment: components["schemas"]["ExperimentConfig"];
            sensor?: {
                [key: string]: unknown;
            };
            waveform: components["schemas"]["WaveformConfig"];
        };
        VizTriggerEvent: {
            class: string;
            timestamp: string;
            visible: boolean;
        };
        WT901Config: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/WT901Config.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Accel smoothing (0=raw, 1-15)
             * @default 0
             */
            accel_filter: number;
            /**
             * @description Accelerometer range (±g)
             * @default 4
             * @enum {integer}
             */
            accel_range_g: 2 | 4 | 8 | 16;
            /**
             * @description Low-pass filter cutoff (Hz)
             * @default 256
             * @enum {integer}
             */
            bandwidth_hz: 5 | 10 | 21 | 44 | 94 | 184 | 256;
            /**
             * @description Output rate (Hz)
             * @default 50
             * @enum {integer}
             */
            output_rate_hz: 10 | 20 | 50 | 100 | 200;
            /**
             * @description 6-axis mode (disable magnetometer)
             * @default true
             */
            six_axis: boolean;
        };
        WaveformConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/WaveformConfig.json
             */
            readonly $schema?: string;
            /**
             * Format: double
             * @description Amplitude multiplier
             * @default 1
             */
            amp_scale: number;
            /**
             * Format: int64
             * @description Ring buffer sample count
             * @default 256
             */
            buffer_size: number;
            /**
             * @description Enable visualization
             * @default true
             */
            enabled: boolean;
            /**
             * Format: double
             * @description Red threshold (g)
             * @default 0.1
             */
            force_red_g: number;
            /**
             * Format: double
             * @description Yellow threshold (g)
             * @default 0.03
             */
            force_yellow_g: number;
            /**
             * Format: int64
             * @description Canvas height (px)
             * @default 1080
             */
            height: number;
            /**
             * Format: double
             * @description Log compression knee
             * @default 0.02
             */
            log_knee: number;
            /**
             * Format: int64
             * @description Canvas width (px)
             * @default 608
             */
            width: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post-api-ble-connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-ble-disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-ble-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameStateBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-ble-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameActionRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameStateBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ble-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        data: components["schemas"]["BLEScanResultEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "device";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinQuakeConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-auto-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoLockConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-auto-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoLockConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoLockConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-ble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BLEConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-ble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BLEConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BLEConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-crosshair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosshairConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-crosshair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrosshairConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosshairConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-display": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-display": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisplayConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-sensor-wt901": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WT901Config"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-sensor-wt901": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WT901Config"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WT901Config"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config-waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaveformConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config-waveform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaveformConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaveformConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "events-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["BatteryEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "battery";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["BLEStatusEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "ble-status";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["ConfigChangedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "config-changed";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["HeartbeatEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "heartbeat";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["LogEntry"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "log";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["DelayedOrientationEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "orientation";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["VizTriggerEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "viz-trigger";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
