/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ble/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble connect */
        post: operations["post-api-ble-connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble disconnect */
        post: operations["post-api-ble-disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API ble frame */
        get: operations["get-api-ble-frame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/frame/force-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble frame force lock */
        post: operations["post-api-ble-frame-force-lock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/frame/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble frame lock */
        post: operations["post-api-ble-frame-lock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/frame/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post API ble frame unlock */
        post: operations["post-api-ble-frame-unlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ble/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * BLE scan SSE stream
         * @description Opening this connection starts scanning; closing it stops scanning
         */
        get: operations["ble-scan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API config */
        get: operations["get-api-config"];
        /** Put API config */
        put: operations["put-api-config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE event stream
         * @description Real-time orientation data and BLE status events
         */
        get: operations["events-stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AutoLockConfig: {
            /**
             * Format: double
             * @description Max change (g) to count as stable
             * @default 0.01
             */
            epsilon: number;
            /**
             * Format: double
             * @description Seconds of stability before auto-lock
             * @default 10
             */
            timeout: number;
        };
        BLEConfig: {
            device_address: string;
            device_name: string;
            sensor_name: string;
        };
        BLEScanResultEvent: {
            address: string;
            name: string;
            /** Format: int64 */
            rssi: number;
            sensor_name?: string;
            timestamp: string;
        };
        BLEStatusEvent: {
            device?: string;
            device_name?: string;
            reason?: string;
            status: string;
            timestamp: string;
        };
        BatteryEvent: {
            /** Format: int32 */
            battery_percent: number;
            /** Format: float */
            battery_volts: number;
            charging: boolean;
            timestamp: string;
        };
        ConfigChangedEvent: {
            timestamp: string;
        };
        ConnectRequestBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ConnectRequestBody.json
             */
            readonly $schema?: string;
            /**
             * @description BLE MAC address
             * @example AA:BB:CC:DD:EE:FF
             */
            address: string;
            /**
             * @description BLE advertised name
             * @example WT901BLE50
             */
            name: string;
        };
        CrosshairConfig: {
            /**
             * Format: int64
             * @description Bar thickness (px)
             * @default 12
             */
            bar_thickness: number;
            /**
             * Format: double
             * @description Red threshold (g)
             * @default 0.1
             */
            force_red_g: number;
            /**
             * Format: double
             * @description Yellow threshold (g)
             * @default 0.03
             */
            force_yellow_g: number;
            /**
             * Format: int64
             * @description Bar segment size (px)
             * @default 10
             */
            segment_size: number;
            /**
             * Format: double
             * @description Exponential smoothing factor
             * @default 0.7
             */
            smoothing: number;
            /**
             * @description Swap X and Y axes
             * @default false
             */
            swap_xy: boolean;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FrameStateBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FrameStateBody.json
             */
            readonly $schema?: string;
            locked: boolean;
        };
        HeartbeatEvent: {
            timestamp: string;
        };
        LogEntry: {
            level: string;
            message: string;
            timestamp: string;
        };
        OKBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OKBody.json
             */
            readonly $schema?: string;
            ok: boolean;
        };
        OrientationEvent: {
            /** Format: float */
            gx: number;
            /** Format: float */
            gy: number;
            /** Format: float */
            gz: number;
            timestamp: string;
        };
        PinQuakeConfig: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PinQuakeConfig.json
             */
            readonly $schema?: string;
            auto_lock: components["schemas"]["AutoLockConfig"];
            ble: components["schemas"]["BLEConfig"];
            crosshair: components["schemas"]["CrosshairConfig"];
            viz: components["schemas"]["VizConfig"];
            waveform: components["schemas"]["WaveformConfig"];
        };
        VizConfig: {
            /**
             * Format: int64
             * @example 1080
             */
            height: number;
            /**
             * Format: int64
             * @example 1920
             */
            width: number;
        };
        WaveformConfig: {
            /**
             * Format: double
             * @description Amplitude multiplier
             * @default 1
             */
            amp_scale: number;
            /**
             * Format: int64
             * @description Ring buffer sample count
             * @default 256
             */
            buffer_size: number;
            /**
             * Format: double
             * @description Red threshold (g)
             * @default 0.1
             */
            force_red_g: number;
            /**
             * Format: double
             * @description Yellow threshold (g)
             * @default 0.03
             */
            force_yellow_g: number;
            /**
             * Format: double
             * @description Log compression knee
             * @default 0.02
             */
            log_knee: number;
            /**
             * @description Swap X and Y axes
             * @default false
             */
            swap_xy: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "post-api-ble-connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequestBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-ble-disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-ble-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameStateBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-ble-frame-force-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-ble-frame-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "post-api-ble-frame-unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OKBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "ble-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": {
                        data: components["schemas"]["BLEScanResultEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "device";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    }[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinQuakeConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "put-api-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinQuakeConfig"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinQuakeConfig"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "events-stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["BatteryEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "battery";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["BLEStatusEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "ble-status";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["ConfigChangedEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "config-changed";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["HeartbeatEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "heartbeat";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["LogEntry"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "log";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["OrientationEvent"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "orientation";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
